export const INITIATE_REQUEST = 'INITIATE_REQUEST';
export const LIST_MEMBERS = 'LIST_MEMBERS';
export const ADD_MEMBER = 'ADD_MEMBER';
export const FETCH_MEMBER = 'FETCH_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const MEMBER_REQUEST_FAILUER = 'MEMBER_REQUEST_FAILUER';